UI/Areas/Admin/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using DTO;

namespace UI.Areas.Admin.Controllers
{
    public class LoginController : Controller
    {
        UserBLL userBLL = new UserBLL();
        // GET: Admin/Login
        public ActionResult Index()
        {
            UserDTO dto = new UserDTO();
            return View(dto);
        }

        [HttpPost]
        public ActionResult Index(UserDTO model)
        {
            if (ModelState.IsValid)
            {
                UserDTO user = userBLL.GetUserWithUsernameAndPassword(model);
                if (user != null)
                {
                    if (user.ID != 0)
                    {
                        UserStatic.UserID = user.ID;
                        UserStatic.isAdmin = user.isAdmin;
                        UserStatic.NameSurname = user.Name;
                        UserStatic.ImagePath = user.ImagePath;
                        LogBLL.AddLog(General.ProcessType.Login, General.TableName.Login, 12);
                        return RedirectToAction("Index", "Post");
                    }
                    else
                    {
                        return View(model);
                    }

                }
            }
            return View(model);
        }
    }
}

UI/Areas/Admin/Controllers/MetaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DTO;
using BLL;

namespace UI.Areas.Admin.Controllers
{
    public class MetaController : Controller
    {
        MetaBLL metaBLL = new MetaBLL();
        // GET: Admin/Meta
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddMeta()
        {
            MetaDTO dto = new MetaDTO();
            return View(dto);
        }

        [HttpPost]
        public ActionResult AddMeta(MetaDTO model)
        {
            if(ModelState.IsValid)
            {
                if (metaBLL.AddMeta(model))
                {
                    ViewBag.ProcessState = General.Message.AddSuccess;
                    ModelState.Clear();
                }else
                {
                    ViewBag.ProcessState = General.Message.GeneralError;
                }
            }else
            {
                ViewBag.ProcessState = General.Message.EmptyArea;
            }
            return View(model);
        }

        public ActionResult MetaList()
        {
            List<MetaDTO> metaDtoList = metaBLL.GetMetaData();
            return View(metaDtoList);
        }

        public ActionResult UpdateMeta(int ID)
        {
            MetaDTO model = new MetaDTO();
            model = metaBLL.GetMetaWithID(ID);
            return View(model);
        }
        [HttpPost]
        public ActionResult UpdateMeta(MetaDTO model)
        {
            if(ModelState.IsValid)
            {
                if(metaBLL.UpdateMeta(model))
                {
                    ViewBag.ProcessState = General.Message.AddSuccess;
                    ModelState.Clear();
                }
                else
                {
                    ViewBag.ProcessState = General.Message.GeneralError;
                }
            }
            else
            {
                ViewBag.ProcessState = General.Message.EmptyArea;
            }
            return View(model);
        }
    }
}

UI/Areas/Admin/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Areas.Admin.Controllers
{
    public class PostController : Controller
    {
        // GET: Admin/Post
        public ActionResult Index()
        {
            return View();
        }
    }
}

UI/Areas/Admin/Controllers/SocialMediaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DTO;
using BLL;
using System.Drawing;
using System.IO;
namespace UI.Areas.Admin.Controllers
{
    public class SocialMediaController : Controller
    {
        SocialMediaBLL bll = new SocialMediaBLL();
        // GET: Admin/SocialMedia
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AddSocialMedia()
        {
            SocialMediaDTO model = new SocialMediaDTO();
            return View(model);
        }
        [HttpPost]
        public ActionResult AddSocialMedia(SocialMediaDTO model)
        {
            if(model.SocialImage == null)
            {
                ViewBag.ProcessState = General.Message.ImageMissing;
            }else if(ModelState.IsValid)
            {
                HttpPostedFileBase postedFile = model.SocialImage;
                Bitmap SocilaMedia = new Bitmap(postedFile.InputStream);
                string ext = Path.GetExtension(postedFile.FileName);
                string filename = "";
                if(ext ==".jpg" || ext == ".jpeg" || ext == ".png" || ext == ".png")
                {
                    string uniquenumber = Guid.NewGuid().ToString();
                    filename = uniquenumber + postedFile.FileName;
                    SocilaMedia.Save(Server.MapPath("~/Areas/Admin/Content/SocialMediaImages/" + filename));
                    model.ImagePath = filename;
                    if(bll.AddSocialMedia(model))
                    {
                        ViewBag.ProcessState = General.Message.AddSuccess;
                        model = new SocialMediaDTO();
                        ModelState.Clear();
                    }else
                    {
                        ViewBag.ProcessState = General.Message.GeneralError;
                    }
                }else
                {
                    ViewBag.ProcessState = General.Message.ExtensionError;
                }
            }else
            {
                ViewBag.ProcessState = General.Message.EmptyArea;
            }
            return View(model);
        }

        public ActionResult SocialMediaList()
        {
            List<SocialMediaDTO> dtoList = new List<SocialMediaDTO>();
            dtoList = bll.GetSocialMedia();
            return View(dtoList);
        }

        public ActionResult UpdateSocialMedia(int ID)
        {
            SocialMediaDTO dto = bll.GetSocialMediaWithID(ID);

            return View(dto);
        }

        [HttpPost]
        public ActionResult UpdateSocialMedia(SocialMediaDTO model)
        {
            if(ModelState.IsValid)
            {
               if(model.SocialImage != null)
               {
                    HttpPostedFileBase postedFile = model.SocialImage;
                    Bitmap SocilaMedia = new Bitmap(postedFile.InputStream);
                    string ext = Path.GetExtension(postedFile.FileName);
                    string filename = "";
                    if (ext == ".jpg" || ext == ".jpeg" || ext == ".png" || ext == ".png")
                    {
                        string uniquenumber = Guid.NewGuid().ToString();
                        filename = uniquenumber + postedFile.FileName;
                        SocilaMedia.Save(Server.MapPath("~/Areas/Admin/Content/SocialMediaImages/" + filename));
                        model.ImagePath = filename;
                        
                    }


                }
                string oldImagePath = bll.UpdateSocialMedia(model);
                if(model.SocialImage != null)
                {
                    if(System.IO.File.Exists(Server.MapPath("~/Areas/Admin/Content/SocialMediaImages/" +oldImagePath)))
                    {
                        System.IO.File.Delete(Server.MapPath("~/Areas/Admin/Content/SocialMediaImages/" + oldImagePath));
                    }
                }
                model = new SocialMediaDTO();
                ViewBag.ProcessState = General.Message.UpdateSuccess;
            }
            else
            {
                ViewBag.ProcessState = General.Message.EmptyArea;
            }
            return View(model);
        }
    }
}

UI/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DTO;
using BLL;

namespace UI.Areas.Admin.Controllers
{
    public class UserController : Controller
    {
        // GET: Admin/User
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddUser()
        {
            UserDTO dto = new UserDTO();

            return View(dto);
        }

        
    }
}

UI/Areas/Admin/Views/Login/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = null;
}
@model DTO.UserDTO

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>OAK | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->

    <link href="~/Areas/Admin/Content/CSS/all.min.css" rel="stylesheet" />
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link href="~/Areas/Admin/Content/CSS/icheck-bootstrap.min.css" rel="stylesheet" />
    <!-- Theme style -->
    <link href="~/Areas/Admin/Content/CSS/adminlte.min.css" rel="stylesheet" />
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="../../index2.html"><b>OAK</b></a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Sign in to start your session</p>

                <form method="post">
                    @Html.ValidationMessageFor(x => x.Username)
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Username" name="Username">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>

                    </div>

                    @Html.ValidationMessageFor(x => x.Password)
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" placeholder="Password" name="Password">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>

                    </div>


                    <div class="row">

                        <!-- /.col -->
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
                        </div>
                        <!-- /.col -->
                    </div>
                </form>


                <!-- /.social-auth-links -->


            </div>
            <!-- /.login-card-body -->
        </div>
    </div>
    <!-- /.login-box -->
    <!-- jQuery -->
    <script src="~/Areas/Admin/Content/JS/jquery.min.js"></script>>
    <!-- Bootstrap 4 -->
    <script src="~/Areas/Admin/Content/JS/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Areas/Admin/Content/JS/adminlte.min.js"></script>

</body>
</html>

UI/Areas/Admin/Views/Meta/AddMeta.cshtml
@{
    ViewBag.Title = "AddMeta";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<section class="content-header">

    <h1>Add Meta operation</h1>
    <ul class="breadcrumb float-sm-left">
        <li class="breadcrumb-item"><a>Admin</a></li>
        <li class="breadcrumb-item"><a>Meta</a></li>
        <li class="breadcrumb-item active"><a>Add Meta</a></li>
    </ul>
</section>
<br />
<div class="card-footer">
    <a href="/Admin/Meta/MetaList" class="btn btn-primary">Meta List</a>
</div>
<section class="content">
    <div class="row">
        <div class="col-md-9">
            @Html.Partial("~/Areas/Admin/Views/Shared/MessageForm.cshtml")
            <div class="box box-primary">
                @using (Html.BeginForm("AddMeta", "Meta", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {
                    @Html.Partial("Partial/MetaForm")
                }
            </div>
        </div>
    </div>
</section>

UI/Areas/Admin/Views/Meta/MetaList.cshtml
@{
    ViewBag.Title = "MetaList";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}
@model List<DTO.MetaDTO>
<section class="content-header">

    <h1>Meta List</h1>
    <ul class="breadcrumb float-sm-left">
        <li class="breadcrumb-item"><a>Admin</a></li>
        <li class="breadcrumb-item"><a>Meta</a></li>
        <li class="breadcrumb-item active"><a>Meta List</a></li>
    </ul>
</section>
<br />
<div class="card-footer">
    <a href="/Admin/Meta/AddMeta" class="btn btn-primary">Add Meta</a>
</div>
<div class="card">
    <div class="card-header">
        <h3 class="card-title">DataTable with default features</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Meta Content</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tbody>

                    <tr id="@item.MetaID">
                        <td>@item.Name</td>
                        <td>@item.MetaContent</td>
                        <td align="center" valign="middle">
                            <a href="/Admin/Meta/UpdateMeta/@item.MetaID">
                                <br />
                                <img src="~/Areas/Admin/Content/icons/updates-16.ico" />
                            </a>
                        </td>
                        <td align="center" valign="middle">
                            <a href="#">
                                <br />
                                <img src="~/Areas/Admin/Content/icons/delete-16.ico" />
                            </a>
                        </td>
                    </tr>
                </tbody>
            }

            <tfoot>
                <tr>
                    <th>Name</th>
                    <th>Meta Content</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </tfoot>
        </table>
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->

UI/Areas/Admin/Views/Meta/Partial/MetaForm.cshtml
@model DTO.MetaDTO
<div class="card-body">
    <div class="form-group">
        <label>Meta Content</label>
        @Html.TextBoxFor(x => x.MetaContent, new { @class = "form-control", @placeholder = "Meta Content" })
    </div>
    <div class="form-group">
        <label>Name</label>
        @Html.DropDownList("Name", new SelectList(new[] { "Keywords", "Descriptions", "Author", "Twittercard" }), new { @class = "form-control select2" })
    </div>
    <input type="number" name="MetaID" value="@Model.MetaID" hidden />
    <div class="card-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</div>

UI/Areas/Admin/Views/Meta/UpdateMeta.cshtml
@{
    ViewBag.Title = "UpdateMeta";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<section class="content-header">

    <h1>Update Meta operation</h1>
    <ul class="breadcrumb float-sm-left">
        <li class="breadcrumb-item"><a>Admin</a></li>
        <li class="breadcrumb-item"><a>Meta</a></li>
        <li class="breadcrumb-item active"><a>Add Meta</a></li>
    </ul>
</section>
<br />
<div class="card-footer">
    <a href="/Admin/Meta/MetaList" class="btn btn-primary">Meta List</a>
</div>
<section class="content">
    <div class="row">
        <div class="col-md-9">
            @Html.Partial("~/Areas/Admin/Views/Shared/MessageForm.cshtml")
            <div class="box box-primary">
                @using (Html.BeginForm("UpdateMeta", "Meta", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {
                    @Html.Partial("Partial/MetaForm")
                }
            </div>
        </div>
    </div>
</section>

UI/Areas/Admin/Views/Post/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<h2>Index</h2>

UI/Areas/Admin/Views/Shared/MessageForm.cshtml
@using UI.Areas.Admin;

@if (ViewBag.ProcessState == BLL.General.Message.AddSuccess)
{
    <div class="alert alert-success">
        <strong>Success!! Add Operation was completed Successfully</strong>
    </div>
}
else if (ViewBag.ProcessState == BLL.General.Message.EmptyArea)
{
    <div class="alert alert-danger">
        <strong>Error!! Please fill neccessary area</strong>
    </div>
}
else if (ViewBag.ProcessState == BLL.General.Message.UpdateSuccess)
{
    <div class="alert alert-success">
        <strong>Success!! Update Operation was completed Successfully</strong>
    </div>
}
else if (ViewBag.ProcessState == BLL.General.Message.ImageMissing)
{
    <div class="alert alert-danger">
        <strong>Error!! Please select an Image</strong>
    </div>
}
else if (ViewBag.ProcessState == BLL.General.Message.ExtensionError)
{
    <div class="alert alert-danger">
        <strong>Error!! Please select fill with true extension</strong>
    </div>
}
else if (ViewBag.ProcessState == BLL.General.Message.GeneralError)
{
    <div class="alert alert-danger">
        <strong>Error!!</strong>
    </div>
}

UI/Areas/Admin/Views/SocialMedia/AddSocialMedia.cshtml
@{
    ViewBag.Title = "AddSocialMedia";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<section class="content-header">

    <h1>Add Social Media</h1>
    <ul class="breadcrumb float-sm-left">
        <li class="breadcrumb-item"><a>Admin</a></li>
        <li class="breadcrumb-item"><a>Social Media</a></li>
        <li class="breadcrumb-item active"><a>Add Social Media</a></li>
    </ul>
</section>
<br />
<div class="card-footer">
    <a href="/Admin/SocialMedia/SocialMediaList" class="btn btn-primary">Social Media List</a>
</div>
<section class="content">
    <div class="row">
        <div class="col-md-9">
            @Html.Partial("~/Areas/Admin/Views/Shared/MessageForm.cshtml")
            <div class="box box-primary">
                @using (Html.BeginForm("AddSocialMedia", "SocialMedia", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {
                    @Html.Partial("Partial/SocialMediaForm")
                }
            </div>
        </div>
    </div>
</section>

UI/Areas/Admin/Views/SocialMedia/Partial/SocialMediaForm.cshtml
@model DTO.SocialMediaDTO
    <div class="box-body">
        <div class="form-group">
            <label>Name</label>
            @Html.TextBoxFor(x => x.Name,new  { @class="form-control",@placeholder="Social Media Name"})
            @Html.ValidationMessageFor(x=> x.Name)
        </div>

        <div class="form-group">
            <label>Link</label>
            @Html.TextBoxFor(x=> x.Link,new  { @class="form-control",@placeholder="Social Media Link"})
            @Html.ValidationMessageFor(x => x.Link)
        </div>

        <input hidden type="number" value="@Model.ID" name="ID" />
        <div class="form-group">
            @Html.LabelFor(x => x.SocialImage)
            <input type="file" name="SocialImage" 
                   accept="image/gif, image/jpeg,image/png,image/jpg" 
                   onchange="$('#SocialImage')[0].src= window.URL.createObjectURL(this.files[0])"/>
            <br/>
            @if (Model != null && Model.ImagePath != null)
            {


                <br />


                <img src="~/Areas/Admin/Content/SocialMediaImages/@Model.ImagePath" width="300" height="200"  />
            }
            else
            {
                <img src="" width="300" height="200" id="SocialImage" />
            }
        </div>

         <div class="card-footer">
             <button class="btn btn-primary">Save</button>
         </div>
    </div>

UI/Areas/Admin/Views/SocialMedia/SocialMediaList.cshtml
@{
    ViewBag.Title = "SocialMediaList";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

@model List<DTO.SocialMediaDTO>
<section class="content-header">

    <h1>Meta List</h1>
    <ul class="breadcrumb float-sm-left">
        <li class="breadcrumb-item"><a>Admin</a></li>
        <li class="breadcrumb-item"><a>Social Media</a></li>
        <li class="breadcrumb-item active"><a>Social Media List</a></li>
    </ul>
</section>
<br />
<div class="card-footer">
    <a href="/Admin/SocialMedia/AddSocialMedia" class="btn btn-primary">Add SocialMedia</a>
</div>
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Social Media Link</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Link</th>
                    <th>Image</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tbody>

                    <tr id="@item.ID">
                        <td>@item.Name</td>
                        <td><a href="@item.Link">@item.Name</a></td>
                        <td>
                            <img src="~/Areas/Admin/Content/SocialMediaImages/@item.ImagePath" width="60" height="40" />
                        </td>
                        <td align="center" valign="middle">
                            <a href="/Admin/SocialMedia/UpdateSocialMedia/@item.ID">
                                <br />
                                <img src="~/Areas/Admin/Content/icons/updates-16.ico" />
                            </a>
                        </td>
                        <td align="center" valign="middle">
                            <a href="#">
                                <br />
                                <img src="~/Areas/Admin/Content/icons/delete-16.ico" />
                            </a>
                        </td>
                    </tr>
                </tbody>
            }

            <tfoot>
                <tr>
                    <th>Name</th>
                    <th>Link</th>
                    <th>Image</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </tfoot>
        </table>
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->

UI/Areas/Admin/Views/SocialMedia/UpdateSocialMedia.cshtml
@{
    ViewBag.Title = "UpdateSocialMedia";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<section class="content-header">

    <h1>Update Social Media</h1>
    <ul class="breadcrumb float-sm-left">
        <li class="breadcrumb-item"><a>Admin</a></li>
        <li class="breadcrumb-item"><a>Social Media</a></li>
        <li class="breadcrumb-item active"><a>Update Social Media</a></li>
    </ul>
</section>
<br />
<div class="card-footer">
    <a href="/Admin/SocialMedia/SocialMediaList" class="btn btn-primary">Social Media List</a>
</div>
<section class="content">
    <div class="row">
        <div class="col-md-9">
            @Html.Partial("~/Areas/Admin/Views/Shared/MessageForm.cshtml")
            <div class="box box-primary">
                @using (Html.BeginForm("UpdateSocialMedia", "SocialMedia", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {
                    @Html.Partial("Partial/SocialMediaForm")
                }
            </div>
        </div>
    </div>
</section>

UI/Areas/Admin/Views/User/AddUser.cshtml
@{
    ViewBag.Title = "AddUser";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<section class="content-header">

    <h1>Add User</h1>
    <ul class="breadcrumb float-sm-left">
        <li class="breadcrumb-item"><a>Admin</a></li>
        <li class="breadcrumb-item"><a>User</a></li>
        <li class="breadcrumb-item active"><a>Add User</a></li>
    </ul>
</section>
<br />
<div class="card-footer">
    <a href="/Admin/User/UserList" class="btn btn-primary">User List</a>
</div>
<section class="content">
    <div class="row">
        <div class="col-md-9">
            @Html.Partial("~/Areas/Admin/Views/Shared/MessageForm.cshtml")
            <div class="box box-primary">
                @using (Html.BeginForm("AddUser", "User", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {
                    @Html.Partial("Partial/UserForm")
                }
            </div>
        </div>
    </div>
</section>

UI/Areas/Admin/Views/User/Partial/UserForm.cshtml
@model DTO.UserDTO
<div class="box-body">
    <div class="form-group">
        <label>User Name</label>
        @Html.TextBoxFor(x => x.Username, new { @class = "form-control", @placeholder = "User Name" })
        @Html.ValidationMessageFor(x => x.Username)
    </div>

    <div class="form-group">
        <label>Password</label>
        @Html.TextBoxFor(x => x.Password, new { @class = "form-control", @placeholder = "Password" })
        @Html.ValidationMessageFor(x => x.Password)
    </div>
    <div class="form-check">
        <input type="checkbox" class="form-check-input" name="isAdmin" checked="@Model.isAdmin" value="true">
        <label class="form-check-label">is Admin?</label>
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.UserImage)
        <br />
        <input type="file" name="UserImage"
               accept="image/gif, image/jpeg,image/png,image/jpg"
               onchange="$('#UserImage')[0].src= window.URL.createObjectURL(this.files[0])" />
        <br />
        @if (Model != null && Model.ImagePath != null)
        {


            <br />


            <img src="~/Areas/Admin/Content/UserImage/@Model.ImagePath" width="300" height="200" />
        }
        else
        {
            <img src="" width="300" height="200" id="UserImage" />
        }
    </div>

    <div class="form-group">
        <label>Name</label>
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control", @placeholder = "Name" })
        @Html.ValidationMessageFor(x => x.Name)
    </div>

    <div class="form-group">
        <label>Email</label>
        @Html.TextBoxFor(x => x.Email, new { @class = "form-control", @placeholder = "E-mail" })
        @Html.ValidationMessageFor(x => x.Email)
    </div>

    <input type="number" hidden name="ID" value="@Model.ID"/>
    <div class="card-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>

</div>